---
version: '3'

services:
  app:
    image: app
    env_file: ".env"
    volumes:
       - '.:/app'
       - /app/node_modules/ 
    networks:
      - storybook
    expose:
      - 8081
    build:
      context: .
      dockerfile: docker/Dockerfile
#    restart: on-failure
    # command: /start-local.sh
    ports:
      - "8081:8081"

networks:
  storybook:
    external: false
    driver: bridge